"""Strategy Lab Data Models - BB-FIN-020"""

from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class StrategyCategory(str, Enum):
    """Strategy category classifications."""
    TREND_CONTINUATION = "trend_continuation"
    BREAKOUT_MOMENTUM = "breakout_momentum"
    MEAN_REVERSION = "mean_reversion"
    GAMMA_MAGNET = "gamma_magnet"
    VOLATILITY_COMPRESSION = "volatility_compression"
    LIQUIDITY_SWEEP_REVERSAL = "liquidity_sweep_reversal"
    OPENING_RANGE_BREAKOUT = "opening_range_breakout"
    VWAP_RECLAIM = "vwap_reclaim"
    MOMENTUM_BREAKOUT = "momentum_breakout"
    LIQUIDITY_SWEEP_REVERSAL = "liquidity_sweep_reversal"


class StrategyStatus(str, Enum):
    """Strategy lifecycle status."""
    DISCOVERED = "discovered"
    BACKTESTING = "backtesting"
    TESTING = "testing"
    ACTIVE = "active"
    RETIRED = "retired"
    FAILED = "failed"


class MarketRegime(str, Enum):
    """Market regime types for strategy compatibility."""
    RISK_ON_TREND = "RISK_ON_TREND"
    RISK_ON_MOMENTUM = "RISK_ON_MOMENTUM"
    NEUTRAL_MIXED = "NEUTRAL_MIXED"
    ROTATION_TRANSITION = "ROTATION_TRANSITION"
    RISK_OFF_DEFENSIVE = "RISK_OFF_DEFENSIVE"
    VOLATILITY_STRESS = "VOLATILITY_STRESS"
    LIQUIDITY_DISLOCATION = "LIQUIDITY_DISLOCATION"
    RANGE_COMPRESSION = "RANGE_COMPRESSION"
    MEAN_REVERSION = "MEAN_REVERSION"
    MACRO_EVENT_UNCERTAINTY = "MACRO_EVENT_UNCERTAINTY"


class TradeDirection(str, Enum):
    """Trade direction."""
    LONG = "long"
    SHORT = "short"
    BOTH = "both"


class SignalStrength(str, Enum):
    """Signal strength classification."""
    WEAK = "weak"
    MODERATE = "moderate"
    STRONG = "strong"


class EntryCondition(BaseModel):
    """Entry condition definition."""
    condition_type: str  # e.g., "price_above_ema", "volume_spike", "breakout"
    parameter: str  # e.g., "EMA_20", "200%"
    value: Optional[float] = None
    lookback_periods: Optional[int] = None


class ExitCondition(BaseModel):
    """Exit condition definition."""
    condition_type: str  # e.g., "trailing_stop", "固定_target", "time_based"
    parameter: str
    value: Optional[float] = None
    periods: Optional[int] = None


class PositionSizing(BaseModel):
    """Position sizing configuration."""
    method: str  # "fixed_dollar", "percent_risk", "kelly", "volatility_adjusted"
    value: float  # e.g., 1000 for fixed dollar, 0.02 for 2% risk
    max_positions: int = 5


class StrategyDefinition(BaseModel):
    """Complete strategy definition."""
    strategy_id: str
    name: str
    description: str
    category: StrategyCategory
    version: str = "1.0.0"
    status: StrategyStatus = StrategyStatus.DISCOVERED
    
    # Entry/Exit rules
    entry_conditions: List[EntryCondition] = Field(default_factory=list)
    exit_conditions: List[ExitCondition] = Field(default_factory=list)
    
    # Position management
    position_sizing: PositionSizing
    
    # Target instruments
    target_assets: List[str] = Field(default_factory=list)  # e.g., ["SPY", "QQQ"]
    asset_classes: List[str] = Field(default_factory=list)  # e.g., ["equity", "options"]
    
    # Trade direction
    trade_direction: TradeDirection = TradeDirection.BOTH
    
    # Timeframe
    timeframe: str = "intraday"  # intraday, daily, weekly
    
    # Regime compatibility
    compatible_regimes: List[MarketRegime] = Field(default_factory=list)
    incompatible_regimes: List[MarketRegime] = Field(default_factory=list)
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    created_by: str = "system"
    tags: List[str] = Field(default_factory=list)


class StrategySignal(BaseModel):
    """Signal generated by a strategy."""
    strategy_id: str
    strategy_name: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    # Signal details
    direction: TradeDirection
    strength: SignalStrength
    confidence: float = Field(ge=0.0, le=1.0)
    
    # Entry details
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    target_price: Optional[float] = None
    position_size: Optional[float] = None
    
    # Reasoning
    rationale: List[str] = Field(default_factory=list)
    
    # Market context
    current_regime: Optional[MarketRegime] = None
    regime_confidence: Optional[float] = None


class BacktestTrade(BaseModel):
    """Individual trade from backtesting."""
    trade_id: str
    strategy_id: str
    entry_time: datetime
    exit_time: Optional[datetime] = None
    
    # Trade details
    symbol: str
    direction: TradeDirection
    entry_price: float
    exit_price: Optional[float] = None
    
    # Position
    quantity: float
    position_value: float
    
    # P&L
    pnl: float = 0.0
    pnl_percent: float = 0.0
    realized_pnl: float = 0.0
    
    # Status
    status: str = "open"  # open, closed
    
    # Notes
    entry_reason: str = ""
    exit_reason: str = ""


class BacktestResult(BaseModel):
    """Results from a single backtest run."""
    backtest_id: str
    strategy_id: str
    
    # Time range
    start_date: datetime
    end_date: datetime
    
    # Trades
    trades: List[BacktestTrade] = Field(default_factory=list)
    
    # Summary metrics
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    
    # Returns
    total_return: float = 0.0
    total_return_percent: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    
    # Timing
    avg_holding_period_hours: float = 0.0
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)


class PerformanceMetrics(BaseModel):
    """Comprehensive performance metrics."""
    # Return metrics
    total_return: float = 0.0
    annualized_return: float = 0.0
    
    # Risk metrics
    volatility: float = 0.0
    max_drawdown: float = 0.0
    max_drawdown_percent: float = 0.0
    downside_deviation: float = 0.0
    
    # Risk-adjusted metrics
    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0
    calmar_ratio: float = 0.0
    
    # Trade statistics
    win_rate: float = 0.0
    loss_rate: float = 0.0
    profit_factor: float = 0.0
    expectancy: float = 0.0
    avg_trade: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    largest_win: float = 0.0
    largest_loss: float = 0.0
    
    # Trade counts
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    
    # Time metrics
    avg_holding_period_hours: float = 0.0
    trades_per_month: float = 0.0
    
    # Consistency
    return_std_dev: float = 0.0
    monthly_hit_rate: float = 0.0


class MonteCarloSimulation(BaseModel):
    """Monte Carlo simulation results."""
    simulation_id: str
    strategy_id: str
    
    # Configuration
    num_simulations: int
    num_trades_per_sim: int
    
    # Time range used
    start_date: datetime
    end_date: datetime
    
    # Distribution metrics
    mean_return: float = 0.0
    median_return: float = 0.0
    std_deviation: float = 0.0
    
    # Percentile returns
    percentile_5: float = 0.0
    percentile_10: float = 0.0
    percentile_25: float = 0.0
    percentile_75: float = 0.0
    percentile_90: float = 0.0
    percentile_95: float = 0.0
    
    # Drawdown metrics
    avg_max_drawdown: float = 0.0
    median_max_drawdown: float = 0.0
    worst_drawdown: float = 0.0
    prob_ruin: float = 0.0  # Probability of losing >50%
    
    # Win rate distribution
    avg_win_rate: float = 0.0
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)


class RegimePerformance(BaseModel):
    """Strategy performance under a specific regime."""
    regime: MarketRegime
    num_trades: int = 0
    
    # Performance
    return_percent: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    
    # Risk
    max_drawdown: float = 0.0
    volatility: float = 0.0
    
    # Sample quality
    statistical_significance: float = 0.0  # 0-1 confidence
    sample_size_adequate: bool = False


class StrategyRobustnessProfile(BaseModel):
    """Overall strategy robustness assessment."""
    strategy_id: str
    
    # Monte Carlo results
    monte_carlo: Optional[MonteCarloSimulation] = None
    
    # Regime performance
    regime_performance: List[RegimePerformance] = Field(default_factory=list)
    
    # Robustness scores
    stability_score: float = 0.0  # 0-1
    consistency_score: float = 0.0  # 0-1
    tail_risk_score: float = 0.0  # 0-1 (higher = more risky)
    
    # Validation
    overfitting_detected: bool = False
    overfitting_confidence: float = 0.0
    
    # Sample adequacy
    min_sample_size: int = 30
    actual_sample_size: int = 0
    sample_adequate: bool = False
    
    # Overall assessment
    is_robust: bool = False
    readiness_level: str  # "not_ready", "experimental", "qualified", "production"
    
    # Recommendations
    recommendations: List[str] = Field(default_factory=list)


class StrategyRanking(BaseModel):
    """Strategy ranking entry."""
    rank: int
    strategy_id: str
    strategy_name: str
    category: StrategyCategory
    
    # Composite score components
    sharpe_score: float = 0.0
    consistency_score: float = 0.0
    robustness_score: float = 0.0
    regime_adaptation_score: float = 0.0
    
    # Overall
    composite_score: float = 0.0
    
    # Performance summary
    performance_summary: str = ""


class StrategyLeaderboard(BaseModel):
    """Complete strategy leaderboard."""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    # Rankings
    top_strategies: List[StrategyRanking] = Field(default_factory=list)
    emerging_strategies: List[StrategyRanking] = Field(default_factory=list)
    retired_strategies: List[StrategyRanking] = Field(default_factory=list)
    
    # Summary
    total_strategies: int = 0
    active_strategies: int = 0
    experimental_strategies: int = 0


class StrategySimulationReport(BaseModel):
    """Complete strategy analysis report."""
    report_id: str
    strategy_id: str
    strategy_name: str
    
    # Timing
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    analysis_period_start: datetime
    analysis_period_end: datetime
    
    # Strategy definition
    definition: StrategyDefinition
    
    # Backtest results
    backtest: Optional[BacktestResult] = None
    
    # Performance metrics
    metrics: Optional[PerformanceMetrics] = None
    
    # Monte Carlo
    monte_carlo: Optional[MonteCarloSimulation] = None
    
    # Regime analysis
    regime_performance: List[RegimePerformance] = Field(default_factory=list)
    
    # Robustness
    robustness: Optional[StrategyRobustnessProfile] = None
    
    # Overall
    is_recommended: bool = False
    recommendation_reason: str = ""
    
    # Metadata
    version: str = "1.0.0"


class StrategyLabStatus(BaseModel):
    """Strategy lab status overview."""
    # Lab state
    is_initialized: bool = False
    last_analysis_time: Optional[datetime] = None
    
    # Counts
    total_strategies: int = 0
    active_strategies: int = 0
    backtesting_strategies: int = 0
    
    # Latest
    latest_backtest: Optional[datetime] = None
    latest_monte_carlo: Optional[datetime] = None
    latest_ranking: Optional[datetime] = None
    
    # Dependencies
    regime_intelligence_available: bool = False
    market_replay_available: bool = False
    alpha_engine_available: bool = False
