"""Financial Recommendation - represents an actionable financial recommendation."""
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional


class Priority(str, Enum):
    """Priority levels for recommendations."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ActionClass(str, Enum):
    """Classification of recommendation action type."""
    ADVISORY = "advisory"
    APPROVAL_REQUIRED = "approval_required"
    GOVERNANCE_REQUIRED = "governance_required"


@dataclass
class FinancialRecommendation:
    """Represents an actionable financial recommendation generated by the intelligence engine."""
    recommendation_id: str
    profile_id: int
    title: str
    summary: str
    rationale: str
    priority: Priority
    confidence_score: float
    expected_benefit: str
    downside_risk: str
    action_class: ActionClass
    created_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "recommendation_id": self.recommendation_id,
            "profile_id": self.profile_id,
            "title": self.title,
            "summary": self.summary,
            "rationale": self.rationale,
            "priority": self.priority.value,
            "confidence_score": self.confidence_score,
            "expected_benefit": self.expected_benefit,
            "downside_risk": self.downside_risk,
            "action_class": self.action_class.value,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    @classmethod
    def create(
        cls,
        profile_id: int,
        title: str,
        summary: str,
        rationale: str,
        priority: Priority,
        confidence_score: float,
        expected_benefit: str,
        downside_risk: str,
        action_class: ActionClass = ActionClass.ADVISORY,
    ) -> "FinancialRecommendation":
        """Create a new financial recommendation."""
        import uuid
        return cls(
            recommendation_id=str(uuid.uuid4()),
            profile_id=profile_id,
            title=title,
            summary=summary,
            rationale=rationale,
            priority=priority,
            confidence_score=confidence_score,
            expected_benefit=expected_benefit,
            downside_risk=downside_risk,
            action_class=action_class,
        )
